myscrumy/charlesmaryayoscrumy/urls.py
from . import views
from django.urls import path, include

app_name = 'charlesmaryayoscrumy'
urlpatterns = [
   
    path('', views.index, name='index'),
    path('movegoal/<int:goal_id>', views.move_goal, name='movegoal'),
    path('addgoal', views.add_goal, name='addgoal'),
    path('home', views.home, name='home'),
    path('logout', views.logout_view, name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),  
    
]

myscrumy/myscrumy/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('charlesmaryayoscrumy/', include('charlesmaryayoscrumy.urls', namespace='charlesmaryayoscrumy')),
    path('websocket/', include('websocket.urls'))
]

myscrumy/charlesmaryayoscrumy/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class ScrumyGoals(models.Model):
    goal_id = models.IntegerField()
    goal_name = models.CharField(max_length=255)
    created_by = models.CharField(max_length=255, blank=True, null=True)
    moved_by = models.CharField(max_length=255, blank=True, null=True)
    owner = models.CharField(max_length=255, blank=True, null=True)
    user = models.ForeignKey(User, related_name='user_goals', on_delete=models.CASCADE)
    goal_status = models.ForeignKey("GoalStatus", related_name="goals", on_delete=models.PROTECT)

    def __str__(self):
        return self.goal_name

class ScrumyHistory(models.Model):
    moved_by = models.CharField(max_length=255)
    created_by = models.CharField(max_length=255)
    moved_from = models.CharField(max_length=255)
    moved_to = models.CharField(max_length=255)
    time_of_action = models.DateTimeField()
    goal = models.ForeignKey("ScrumyGoals", on_delete=models.PROTECT)

    def __str__(self):
        return self.created_by
    
class GoalStatus(models.Model):
    status_name = models.CharField(max_length=255)

    def __str__(self):
        return self.status_name

myscrumy/charlesmaryayoscrumy/forms.py
from .models import User, ScrumyGoals
from django.forms import ModelForm, Form
from django import forms 


class SignUpForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password']

class CreateGoalForm(ModelForm):
    class Meta:
        model = ScrumyGoals
        fields = ['goal_name', 'user', 'goal_status', 'goal_id']



class MoveGoalForm(Form):
    choices = (
        ('Daily Goal', 'Daily Goal'), 
        ('Weekly Goal', 'Weekly Goal'), 
        ('Done Goal', 'Done Goal'), 
        ('Verify Goal', 'Verify Goal')
        )
    status_name = forms.ChoiceField(choices=choices)

myscrumy/charlesmaryayoscrumy/views.py
from django.contrib.auth.models import Group
from django.contrib.auth.hashers import make_password
from django.contrib.auth import logout
from django.contrib import messages
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import ScrumyGoals, GoalStatus, User
from .forms import CreateGoalForm, SignUpForm, MoveGoalForm
import random
# Create your views here.


def index(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.password = make_password(form.cleaned_data['password'])
            new_user.save()

            developer_group = Group.objects.get(name="Developer")
            new_user = User.objects.get(username=form.cleaned_data['username'])
            developer_group.user_set.add(new_user)
            messages.success(request, 'Your account has been created sucessfully')
            return redirect('/charlesmaryayoscrumy/accounts/login', permanent=True) 
    else:
        form = SignUpForm()
    return render(request, 'index.html', {'form' : form})


def move_goal(request, goal_id):

    current_user = request.user

    dictionary = {
        'error': "There is no record with that goal id"
    }

    try:
        goal = ScrumyGoals.objects.get(goal_id=goal_id)
    except Exception as e:
        return render(request, 'exception.html', dictionary)
    
    if request.method == 'POST':
        form = MoveGoalForm(request.POST)
        if form.is_valid():

            if current_user.groups.filter(name="Developer").exists():
                if form.cleaned_data['status_name'] == "Done Goal":
                    messages.error(request, "Special Permissions are required to perform this operation.")
                    return redirect('charlesmaryayoscrumy:home', permanent=True)
                if goal.user != current_user:
                    messages.error(request, """Special Permissions are required to perform this operation. 
                    Try moving a goal you've created""")
                    return redirect('charlesmaryayoscrumy:home', permanent=True)

            if current_user.groups.filter(name="Quality Assurance").exists():
                if form.cleaned_data['status_name'] == "Weekly Goal":
                    messages.error(request, "Special Permissions are required to perform this operation")
                    return redirect('charlesmaryayoscrumy:home', permanent=True)
                if goal.user != current_user and goal.goal_status.status_name != "Verify Goal":
                    messages.error(request, "You can only move goal's of others if they have been verified")
                    return redirect('charlesmaryayoscrumy:home', permanent=True)

            if current_user.groups.filter(name="Owner").exists():
                if goal.user != current_user:
                    messages.error(request, """Special Permissions are required to perform this operation.
                    Try moving a goal you've created""")
                    return redirect('charlesmaryayoscrumy:home', permanent=True)

            goal.goal_status = GoalStatus.objects.get(status_name=form.cleaned_data['status_name'])
            goal.save()
            messages.success(request, f"The goal has been sucessfully moved to {form.cleaned_data['status_name']}")
            return redirect('charlesmaryayoscrumy:home', permanent=True)
    else:
        form = MoveGoalForm()
    return render(request, 'movegoal.html', {'form':form})


def add_goal(request):

    current_user = request.user
    if request.method == "POST":
        form = CreateGoalForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            if current_user.groups.first().name in ["Developer", "Quality Assurance", "Owner"]:
                if form.cleaned_data['user'] != current_user or \
                    form.cleaned_data['goal_status'].status_name != "Weekly Goal":
                    messages.error(request, "You can only create a weekly goal for yourself")
                    return render(request, 'addgoal.html', {'form': form})
            form.save()
            messages.success(request, "Goal created successfully")
            return redirect('charlesmaryayoscrumy:home', permanent=True)
    else:
        form = CreateGoalForm()

    return render(request, 'addgoal.html', {'form': form})


def home(request):
    data = {
        'users': User.objects.all(),
        'weekly': GoalStatus.objects.get(status_name="Weekly Goal").goals.all(),
        'daily': GoalStatus.objects.get(status_name="Daily Goal").goals.all(),
        'verify': GoalStatus.objects.get(status_name="Verify Goal").goals.all(),
        'done': GoalStatus.objects.get(status_name="Done Goal").goals.all()
    }
    return render(request, 'home.html', data)


def logout_view(request):
    logout(request)
    redirect('charlesmaryayoscrumy:login', permanent=True)

myscrumy/charlesmaryayoscrumy/templates/addgoal.html
<!DOCTYPE html>
<html>
    <head>
        <title>Add Goal</title>
        <style>

            input, select{
              align: center;
              width: 100%;
              padding: 10px 18px;
              margin: 10px 0;
              background-color: white;
              display: block;
              border: 2px solid blue;
              border-radius: 5px;
              box-sizing: border-box;
            }

            div {
                width : 75%;
                margin: auto;
                display : block;
                border-radius: 5px;
                background-color: #f2f2f2;
                padding: 20px;
            }

            input[type=submit] {
                width : 75%;
                align : center;
                background-color: navy;
                color: white;
                padding: 16px 32px;
                margin: 8px 0;
                border: none;
                border-radius: 4px;
                cursor: pointer;
            }
        </style>
    </head>
    <body>
        <h2><a href="{% url 'charlesmaryayoscrumy:home' %}">Home </a> <a href="{% url 'charlesmaryayoscrumy:logout' %}">Logout</a></h2>
        <p>Currrent User: {{ request.user }}</p>
        <p>Groups: {{ request.user.groups.first }}</p><br>

        {% if messages %}
          <ul class="messages">
              {% for message in messages %}
                <li>{{ message }}</li>
              {% endfor %}
          </ul>
        {% endif %}
        <div>
            <form method="POST" action="">
                {% csrf_token %}
                {{ form.as_p }}
                <p><input type="submit" name="submit" value="Submit"></p>
            </form>
        </div>
    </body>
</html>

myscrumy/charlesmaryayoscrumy/templates/exception.html
<!DOCTYPE html>
<html>

<head>
    <title>Error</title>
</head>

<body>
    <p>{{ error }}</p>
</body>

</html>

myscrumy/charlesmaryayoscrumy/templates/home.html
<!DOCTYPE html>
<html>

<head>
    <title>Home</title>
    <style>
        table, th, td {
          border: 1px solid black;
        }
    </style>
</head>

<body>

    <p>Currrent User: {{ request.user }}</p>
    <p>Groups: {{ request.user.groups.first }}</p><br>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <h2><a href="{% url 'charlesmaryayoscrumy:addgoal' %}">Add Goal</a></h2>
    <h2><a href="{% url 'charlesmaryayoscrumy:logout' %}">Logout</a></h2>
    <table>
        <tr>
            <th>User</th>
            <th>Weekly Goals</th>
            <th>Daily Goals</th>
            <th>Verify Goals</th>
            <th>Done Goals</th>
        </tr>
        
        {% for user in users %}
            <tr>
                <td>{{ user }}</td>
                <td>
                    {% for goal in weekly %}
                        {% if goal.user == user %}
                            <a href="{% url 'charlesmaryayoscrumy:movegoal' goal.goal_id %}"> {{ goal.goal_id }} {{goal.goal_name}} </a><br>
                        {% endif %} 
                    {% endfor %}
                </td>
                <td>
                    {% for goal in daily %}
                        {% if goal.user == user%}
                            <a href="{% url 'charlesmaryayoscrumy:movegoal' goal.goal_id %}"> {{ goal.goal_id }} {{goal.goal_name}} </a><br>
                        {% endif %} 
                    {% endfor %}
                </td>
                <td>
                    {% for goal in verify %}
                        {% if goal.user == user%}
                            <a href="{% url 'charlesmaryayoscrumy:movegoal' goal.goal_id %}"> {{ goal.goal_id }} {{goal.goal_name}} </a><br>
                        {% endif %} 
                    {% endfor %}
                </td>
                <td>
                    {% for goal in done %}
                        {% if goal.user == user%}
                            <a href="{% url 'charlesmaryayoscrumy:movegoal' goal.goal_id %}"> {{ goal.goal_id }} {{goal.goal_name}} </a><br>
                        {% endif %} 
                    {% endfor %}
                </td>
            </tr>
                
        {% endfor %}
    </table>
</body>

</html>

myscrumy/charlesmaryayoscrumy/templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>Register</title>
        <style>
         input[type=text]{
              width: 100%;
              padding: 10px 18px;
              margin: 10px 0;
              background-color: lightblue;
              display: block;
              border: 2px solid blue;
              border-radius: 5px;
              box-sizing: border-box;
            }
         input[type = email]{
              width: 100%;
              padding: 10px 18px;
              margin: 10px 0;
              background-color: lightblue;
              display: block;
              border: 2px solid blue;
              border-radius: 5px;
              box-sizing: border-box;
            }
            
            input[type=submit] {
              width: 100%;
              background-color: navy;
              color: white;
              padding: 16px 32px;
              margin: 8px 0;
              border: none;
              border-radius: 4px;
              cursor: pointer;
            }
            
            input[type=submit]:hover {
              background-color: lightblue;
            }
            
            div {
                width: 100%;
              padding: 10px 18px;
              margin: 10px 0;
              border-radius: 5px;
              background-color: #f2f2f2;
              padding: 20px;
              display: inline-block;
              box-sizing: border-box;
            }
        </style>
    </head>
    <body>
    <div>
        <form action = "" method = "POST">
            {% csrf_token %}
            {{ form.as_p}}
            <input type = "submit" name = "submit" value = "Submit" />
        </form>
    </div>
    </body>
</html>

myscrumy/charlesmaryayoscrumy/templates/movegoal.html
<!DOCTYPE html>
<html>
    <head>
        <style>
            input[type=text] {
              width: 100%;
              padding: 10px 18px;
              margin: 10px 0;
              background-color: lightblue;
              display: block;
              border: 2px solid blue;
              border-radius: 5px;
              box-sizing: border-box;
            }
            
            input[type=submit] {
              width: 100%;
              background-color: navy;
              color: white;
              padding: 16px 32px;
              margin: 8px 0;
              border: none;
              border-radius: 4px;
              cursor: pointer;
            }
            
            input[type=submit]:hover {
              background-color: lightblue;
            }
            
            div {
              border-radius: 5px;
              background-color: #f2f2f2;
              padding: 20px;
            }
        </style>
    </head>
    <body>
      <h2><a href="{% url 'charlesmaryayoscrumy:home' %}">Home </a> <a href="{% url 'charlesmaryayoscrumy:logout' %}">Logout</a></h2>
      <p>Currrent User: {{ request.user }}</p>
      <p>Groups: {{ request.user.groups.first }}</p><br>
        <div>
            <form action="" method="POST">
                {% csrf_token %}
                <p>Move to:</p><br>
                {{ form.as_p }}
                <input type="submit" name="submit" value="Submit">
            </form>
        </div>
    </body>
</html>